services:
  redisbroker:
    image: redis
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - redisbroker
      - weaviate
    environment:
      - CELERY_BROKER_URL=redis://redisbroker:6379/0

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - uploads:/app/uploads
    depends_on:
      - redisbroker
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redisbroker:6379/0

  frontend:
    build:
      context: ./pdf-qa-frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend

volumes:
  uploads: